import { Navbar } from "@/components/shared/Navbar";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html
      lang="en"

    >
      <body className=" dark">
        <Toaster position="top-right" richColors />
        {/* <Navbar /> */}
        {children}</body>
      {/* Footer */}
    </html>
  );
}
